services:
  nginx:
    image: nginx:${NGINX_VERSION}
    # 看情况开启
    ports:
      - "8090:8090"
      # - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - xhgui-net
  php56:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP56_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php56.sh
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP56_LOG_DIR}:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - xhgui-net
  mongo:
    image: mongo:${MONGO_VERSION}
    # ports:
      # - "${MONGO_HOST_PORT}:27017"
    volumes:
      - ${MONGO_DATA_DB_DIR}:/data/db:rw
    restart: always
    networks:
      - xhgui-net
    # external: true

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_HOST_PORT}:8081"
    environment:
    - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME}
    - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
    networks:
      - xhgui-net
  
networks:
  xhgui-net:
